apiVersion: v1
kind: Service
metadata:
  name: gitops-workshopeks
  namespace: gitops-workshopeks
  labels:
    app: gitops-workshopeks
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: gitops-workshopeks
