---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-workshopeks
  namespace: gitops-workshopeks
  labels:
    app: gitops-workshopeks
  annotations:
    # Container Image Automated Updates
    flux.weave.works/automated: "true"
    # do not apply this manifest on the cluster
    #flux.weave.works/ignore: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-workshopeks
  template:
    metadata:
      labels:
        app: gitops-workshopeks
    spec:
      containers:
      - name: gitops-workshopeks
        image: 413261866551.dkr.ecr.us-east-1.amazonaws.com/gitops-workshopeks:baed1261
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
